### ISSUE TITLE
Use >5V power supply for agitator

### ISSUE THREAD

**Issue by ptbrown1729** [ries-lab/LaserEngine#2]
A comment (not an issue) which I hope will be helpful to others, since I spent some time troubleshooting when building the agitator module myself.

The electronic speed controller board is power by a 5V regulator, so using a 5V DC power supply may not be sufficient for the regulators to operate properly. A 9V power supply will work fine.

Using the 5V power supply caused me some confusion because the regulator only output 4V, which was enough to power the servo consistency tester but not the ERC.

Thanks for making this design available!

**Comment by dschr** [comment]
Thank you for mentioning this, it is a good point and true indeed. In a new iteration of the engine, we use a 15V input with a different, but similar motor. However, it now needs an active cooling system, which we wanted and still want to leave out. So, I plan to test at some point a more expensive, yet efficient motor.

**Comment by jdeschamps** [comment]
Actually there is a mistake indeed in the current guide (Motor V2). We actually are using a 12 V and not a 5 V power supply. 

Thanks for catching this @ptbrown1729 ! Let us know if the update to the motor V2 guide now makes sense and we can close the issue.

**Comment by jdeschamps** [comment]
I consider it closed!

best
